import type { Metadata } from "next";
import "./globals.css";
import { DM_Serif_Display, Manrope } from "next/font/google";
import FloatingWhatsappWidget from "./components/layout/sections/FloatingWhatsappWidget";

const headingFont = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-heading",
  display: "swap",
});

const bodyFont = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${headingFont.variable} ${bodyFont.variable}`}
    >
      <body className="font-sansBody antialiased min-h-full flex flex-col">{children}</body>
      <FloatingWhatsappWidget />
    </html>
  );
}
